import { Quote, Lead } from '@prisma/client'
import { Resend } from 'resend'

const resend = process.env.RESEND_API_KEY 
  ? new Resend(process.env.RESEND_API_KEY)
  : null;

type QuoteWithLead = Quote & {
  lead: Lead;
};

export async function sendQuoteEmail(quote: QuoteWithLead) {
  try {
    const { lead } = quote;
    
    // In development, log the email instead of sending it
    if (!resend || process.env.NODE_ENV === 'development') {
      console.log('Development mode - Email would be sent:', {
        to: lead.email,
        subject: `Your Same Day Ramps Quote - ${quote.rampLength}ft Ramp`,
        quote: quote,
      });
      return { success: true, data: { id: 'dev-mode' } };
    }
    
    const { data, error } = await resend.emails.send({
      from: 'Same Day Ramps <onboarding@resend.dev>', // Update this once you verify your domain
      to: lead.email,
      subject: `Your Same Day Ramps Quote - ${quote.rampLength}ft Ramp`,
      html: `
        <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
          <h1 style="color: #333;">Quote for ${lead.firstName} ${lead.lastName}</h1>
          <p>Thank you for your interest in Same Day Ramps. Here are the details of your quote:</p>
          
          <div style="background-color: #f8f9fa; padding: 20px; border-radius: 8px; margin: 20px 0;">
            <h2 style="color: #333; margin-top: 0;">Quote Details:</h2>
            <ul style="list-style: none; padding: 0;">
              <li style="margin-bottom: 10px;">🔹 Ramp Length: ${quote.rampLength} ft</li>
              <li style="margin-bottom: 10px;">🔹 Platforms: ${quote.platforms}</li>
              <li style="margin-bottom: 10px;">🔹 Total Price: $${quote.price.toFixed(2)}</li>
            </ul>
            
            <p style="margin-top: 20px; font-weight: bold;">
              Valid until: ${quote.expiresAt ? new Date(quote.expiresAt).toLocaleDateString() : 'N/A'}
            </p>
          </div>
          
          ${quote.notes ? `
            <div style="background-color: #fff3cd; padding: 15px; border-radius: 8px; margin: 20px 0;">
              <strong>Additional Notes:</strong><br>
              ${quote.notes}
            </div>
          ` : ''}
          
          <div style="margin-top: 30px; padding-top: 20px; border-top: 1px solid #eee;">
            <p style="color: #666;">
              To proceed with this quote or if you have any questions, please contact us at:
              <br>
              📞 <a href="tel:+1234567890" style="color: #0066cc; text-decoration: none;">123-456-7890</a>
              <br>
              ✉️ <a href="mailto:info@samedayramps.com" style="color: #0066cc; text-decoration: none;">info@samedayramps.com</a>
            </p>
          </div>
          
          <div style="margin-top: 30px; font-size: 12px; color: #666; text-align: center;">
            <p>This quote was generated by Same Day Ramps CRM</p>
          </div>
        </div>
      `,
      replyTo: "info@samedayramps.com",
    });

    if (error) {
      console.error('Resend API error:', error);
      return { success: false, error };
    }

    return { success: true, data };
  } catch (error) {
    console.error('Failed to send quote email:', error);
    return { success: false, error };
  }
} 